In [1]:
import pandas as pd

In [2]:
# Define a list of common surname prefixes
surname_prefixes = ['van', 'van der', 'de', 'le', 'la', 'van de', 'Van', 'Van der', 'Van Der', 'Van De', 'De']
# Specify the path to your data file and the columns you want to keep
file_path = 'LILAC Participants - Form Responses 1.csv'
columns_to_keep = ['First and last name',
                   'Affiliation',
                   'For virtual attendees: what time zone will you be joining from?']

# Function to transform time zone information into attendance type
def transform_attendance(column):
    """
    Transforms time zone information into attendance type ('Virtual' or 'In Person').

    Parameters:
    - column: The pandas Series (column) with time zone or blank values.

    Returns:
    - Transformed pandas Series with 'Virtual' for non-blank entries and 'In Person' for blank entries.
    """
    return column.apply(lambda x: 'Virtual' if pd.notnull(x) and x.strip() != '' else 'In Person')

def extract_surname(name):
    """
    Extracts the surname from a full name, correctly handling known surname prefixes.
    """
    parts = name.split()
    # Reverse the name parts to start checking from the end
    parts.reverse()
    surname_parts = [parts[0]]  # Start with the last part of the name

    # Check if the preceding part is a known prefix and add it to the surname if so
    for part in parts[1:]:
        if part.lower() in surname_prefixes:
            surname_parts.append(part)
        else:
            break  # Stop if a part is not a known prefix

    # Return the surname, which is the last name part and any prefixes, reversed back to the correct order
    return ' '.join(reversed(surname_parts))

# Read the data file
df = pd.read_csv(file_path, usecols=columns_to_keep)

# Apply the transformation function and adjust column names
df['Attendance'] = transform_attendance(df['For virtual attendees: what time zone will you be joining from?'])
df.drop(columns=['For virtual attendees: what time zone will you be joining from?'], inplace=True)
df.rename(columns={'First and last name': 'Participant'}, inplace=True)

# Use the extract_surname function to get the surname for sorting
df['Surname'] = df['Participant'].apply(extract_surname)

# Sort the DataFrame by the surname
df.sort_values(by='Surname', inplace=True)

# Add a numbering column, starting from 1, after sorting
df.reset_index(drop=True, inplace=True)
df.index = df.index + 1
df['No.'] = df.index

# Reorder and select the final columns for display, dropping the 'Surname' column used for sorting
df = df[['No.', 'Participant', 'Affiliation', 'Attendance']]

# Convert the DataFrame to an HTML table
html_table = df.to_html(index=False, border=0, classes='participants-table', escape=False)

# Build the HTML content for your participants page with the table
html_content = f"""---
layout: default
title: Participants
order: 5
---
{html_table}
"""

# Print the HTML content to the console or write it to an HTML file
print(html_content)

---
layout: default
title: Participants
order: 5
---
<table class="dataframe participants-table">
  <thead>
    <tr style="text-align: right;">
      <th>No.</th>
      <th>Participant</th>
      <th>Affiliation</th>
      <th>Attendance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Raul Angulo</td>
      <td>DIPC</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Marika Asgari</td>
      <td>Newcastle University</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>3</td>
      <td>Thomas Bakx</td>
      <td>Utrecht University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Avijit Bera</td>
      <td>The University of Texas at Dallas</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>5</td>
      <td>Jonathan Blazek</td>
      <td>Northeastern</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>6</td>
      <td>Elisa Chisari</td>
      <td>Utrecht University</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>7</td>
      <td>Fulvio Ferlito</td>
      <td>Max Planck Institute for Astrophysics (Garching)</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>8</td>
      <td>Silvan Fischbacher</td>
      <td>ETH Zurich</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>9</td>
      <td>Christos Georgiou</td>
      <td>Utrecht University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>10</td>
      <td>David Navarro Gironés</td>
      <td>Institute of Space Sciences (CSIC)</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>11</td>
      <td>Aniruddh Herle</td>
      <td>Leiden Observatory</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>12</td>
      <td>Mustapha Ishak</td>
      <td>University of Texas at Dallas</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>13</td>
      <td>Benjamin Joachimi</td>
      <td>UCL</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>14</td>
      <td>Claire Lamman</td>
      <td>Harvard University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>15</td>
      <td>Constance Mahony</td>
      <td>Donostia International Physics Center</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>16</td>
      <td>Francisco Maion</td>
      <td>Donostia International Physics Center</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>17</td>
      <td>Simon Samuroff</td>
      <td>Northeastern University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>18</td>
      <td>Niko Sarcevic</td>
      <td>Newcastle University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>19</td>
      <td>John Suárez-Pérez</td>
      <td>NaN</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>20</td>
      <td>Isaac Tutusaus</td>
      <td>IRAP-OMP</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>21</td>
      <td>Nick Van Alfen</td>
      <td>Northeastern University</td>
      <td>In Person</td>
    </tr>
    <tr>
      <td>22</td>
      <td>Carter Williams</td>
      <td>Northeastern University</td>
      <td>Virtual</td>
    </tr>
    <tr>
      <td>23</td>
      <td>Marloes van Loon</td>
      <td>Utrecht University</td>
      <td>Virtual</td>
    </tr>
  </tbody>
</table>